version: 2.1


jobs:
  "build":
    docker:
      - image: kiwixz/ci-cpp:2019-08-04
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            pacman --color=always --needed --noconfirm -Sy  \
                libxcursor libxi libxinerama libxrandr  `# glfw`

      - restore_cache:
          name: Restore vcpkg cache
          keys:
            - vcpkg-0-{{ .Branch }}-{{ .Revision }}
            - vcpkg-0-{{ .Branch }}-
            - vcpkg-0-
      - run:
          name: Install vcpkg dependencies
          command: |
            ln -s "/opt/vcpkg"
            mkdir -p "build/vcpkg"
            cd "build/vcpkg"
            cmake "../.."
      - save_cache:
          name: Save vcpkg cache
          key: vcpkg-0-{{ .Branch }}-{{ .Revision }}
          paths:
            - /opt/vcpkg

      - run:
          name: Dump versions
          command: |
            pacman --color=always -Q
            vcpkg list

      - run:
          name: Test debug
          environment:
            CXXFLAGS: -fdiagnostics-color=always
            LDFLAGS: -fdiagnostics-color=always -fuse-ld=lld
            ASAN_OPTIONS: check_initialization_order=1
            UBSAN_OPTIONS: print_stacktrace=1
          command: |
            mkdir -p "build/debug"
            cd "build/debug"
            cmake -G Ninja -D "CMAKE_BUILD_TYPE=Debug" "../.."
            ninja
            ctest --output-on-failure -E "check_.*"
      - run:
          name: Test release
          environment:
            CXXFLAGS: -fdiagnostics-color=always
            LDFLAGS: -fdiagnostics-color=always -fuse-ld=lld
          command: |
            mkdir -p "build/release"
            cd "build/release"
            cmake -G Ninja -D "CMAKE_BUILD_TYPE=Release" "../.."
            ninja
            ctest --output-on-failure -E "check_.*"
      - run:
          name: Additional checks
          command: |
            cd "build/debug"
            ctest --output-on-failure -R "check_.*"


workflows:
  version: 2
  all:
    jobs:
      - "build"
