on: [create, pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
        cxx: ["g++", "clang++"]
    runs-on: ubuntu-latest
    container:
      image: kiwixz/ci-cpp:2019-10-27
    steps:
      - name: Install system dependencies
        run: |
          pacman --color=always --needed --noconfirm -Sy  \
              git openssh  \
              clang cmake gcc lld nasm ninja python  \
              libxcursor libxi libxinerama libxrandr  `# glfw`

      - name: Dump packages versions
        run: |
          pacman --color=always -Q

      - name: Checkout
        run: |
          git clone "https://github.com/${{ github.repository }}" "./"
          git checkout "${{ github.sha }}"

      - name: Configure
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
          CXX: ${{ matrix.cxx }}
          CXXFLAGS: -fdiagnostics-color=always
          LDFLAGS: -fdiagnostics-color=always
        run: |
          ln -s "/opt/vcpkg"
          cmake -G Ninja  \
              -D "CMAKE_BUILD_TYPE=$BUILD_TYPE" -D "CMAKE_CXX_COMPILER=$(which $CXX)"  \
              -S "." -B "build"

      - name: Dump libraries versions
        run: |
          vcpkg list

      - name: Build
        run: |
          ninja -C "build"

      - name: Test
        env:
          ASAN_OPTIONS: check_initialization_order=1:detect_stack_use_after_return=1
          UBSAN_OPTIONS: print_stacktrace=1
        run: |
          ctest --output-on-failure -C "build"


  build_windows:
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
    runs-on: windows-latest
    env:
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
    steps:
      - name: Install system dependencies
        run: |
          choco install nasm

      - name: Checkout
        run: |
          git clone "https://github.com/${{ github.repository }}" "."
          git checkout "${{ github.sha }}"

      - name: Configure
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          cmd /k call "%VCVARS%"
          cmake -G Ninja -D "CMAKE_BUILD_TYPE=$BUILD_TYPE" -S "." -B "build"

      - name: Build
        run: |
          cmd /k call "%VCVARS%"
          ninja -C "build"

      - name: Test
        run: |
          cmd /k call "%VCVARS%"
          ctest --output-on-failure -C "build"
